.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "PHARK\-PATHS" "1" "May 2011" "" ""
.
.SH "NAME"
\fBphark\-paths\fR \- paths used by phark
.
.SH "SYNOPSIS"
Phark uses are variety of paths to install it\'s stuff\. Packages are either installed system\-wide or on a per\-project basis\.
.
.SS "Phark System"
Phark installs by default to \fB/usr/local/phark\fR\. Underneath this is:
.
.IP "\(bu" 4
\fBpackages\fR Site wide packages are stored under here, decompressed from \.phar form\. These are in the form \fBpackage@1\.0\.0\fR\. For more details on version numbers see \fBversions\fR\.
.
.IP "\(bu" 4
\fBactivated\fR The latest activated packages are symbolically linked here\. This is the path that is included in the php \fBinclude_path\fR\. See \fBruntime\fR for more details\.
.
.IP "\(bu" 4
\fBcache\fR Packages are downloaded to this directory before they are installed\. See \fBfetch\fR for more details\.
.
.IP "" 0
.
.P
Underneath a particular project, phark maintains a \fBvendor\fR directory\. This is also included in the php \fBinclude_path\fR and contains a mixture of actual package directories and symbolic links to the system package directories\.
.
.P
In addtion, Phark uses the system temp directory, which defaults to \fB/tmp\fR\.
.
.SH "MORE INFORMATION"
Running under a local project, Phark attempts to find the nearest vendor directory to include\. This is accomplished by starting at the $PWD and iterating up the directory tree\. Once found, the top level is treated as the base directory\.
